export const MATERIAL_SYMBOLS = [
  "search", "home", "menu", "close", "settings", "check", "favorite", "add", "delete", "arrow_back",
  "star", "chevron_right", "logout", "arrow_forward_ios", "add_circle", "cancel", "arrow_back_ios",
  "file_download", "arrow_drop_down", "more_vert", "check_circle", "person", "mail", "edit",
  "visibility", "notifications", "expand_more", "share", "account_circle", "more_horiz", "chevron_left",
  "filter_list", "check_box", "cloud_upload", "refresh", "arrow_forward", "login", "radio_button_unchecked",
  "calendar_today", "help", "shopping_cart", "done", "error", "arrow_upward", "info", "mail_outline",
  "add_box", "arrow_downward", "check_box_outline_blank", "radio_button_checked", "remove_red_eye",
  "cloud_download", "keyboard_arrow_down", "keyboard_arrow_right", "play_arrow", "content_copy",
  "lock", "keyboard_arrow_left", "keyboard_arrow_up", "event", "list", "attach_file", "done_all",
  "sentiment_satisfied", "chat", "group", "schedule", "description", "send", "thumb_up", "warning",
  "local_shipping", "email", "verified", "public", "visibility_off", "history", "language", "face",
  "place", "shopping_bag", "today", "person_add", "credit_card", "camera_alt", "print", "contact_support",
  "save", "star_border", "star_half", "star_outline", "stars", "thumb_down", "verified_user", "work",
  "account_balance", "account_balance_wallet", "build", "cached", "code", "dashboard", "date_range",
  "delete_forever", "delete_outline", "done_outline", "explore", "extension", "feedback", "get_app",
  "grade", "help_outline", "home_work", "important_devices", "input", "label", "label_important",
  "launch", "line_style", "line_weight", "lock_open", "loyalty", "mark_as_unread", "maximize",
  "minimize", "note_add", "offline_bolt", "offline_pin", "opacity", "open_in_browser", "open_in_new",
  "open_with", "pageview", "pan_tool", "payment", "perm_contact_calendar", "perm_device_information",
  "perm_identity", "perm_media", "perm_phone_msg", "perm_scan_wifi", "pets", "power_settings_new",
  "pregnant_woman", "query_builder", "question_answer", "receipt", "record_voice_over", "redeem",
  "remove_shopping_cart", "reorder", "report_problem", "restore", "restore_from_trash", "restore_page",
  "room", "rounded_corner", "rowing", "search_off", "settings_applications", "settings_backup_restore",
  "settings_bluetooth", "settings_brightness", "settings_cell", "settings_ethernet", "settings_input_antenna",
  "settings_input_component", "settings_input_composite", "settings_input_hdmi", "settings_input_svideo",
  "settings_overscan", "settings_phone", "settings_power", "settings_remote", "settings_voice",
  "shop", "shop_two", "shopping_basket", "speaker_notes", "speaker_notes_off", "spellcheck",
  "sticky_note_2", "store", "subject", "supervised_user_circle", "swap_horiz", "swap_vert",
  "swap_vertical_circle", "sync_alt", "system_update_alt", "tab", "tab_unselected", "text_rotate_up",
  "text_rotate_vertical", "text_rotation_angledown", "text_rotation_angleup", "text_rotation_down",
  "text_rotation_none", "theaters", "thumb_down_off_alt", "thumb_up_off_alt", "thumbs_up_down",
  "timeline", "toc", "today", "toll", "touch_app", "tour", "track_changes", "translate", "trending_down",
  "trending_flat", "trending_up", "turned_in", "turned_in_not", "update", "update_disabled", "upgrade",
  "verified", "verified_user", "vertical_split", "view_agenda", "view_array", "view_carousel",
  "view_column", "view_day", "view_headline", "view_list", "view_module", "view_quilt", "view_sidebar",
  "view_stream", "view_week", "visibility", "visibility_off", "voice_over_off", "watch_later",
  "wifi_protected_setup", "work", "work_off", "work_outline", "wysiwyg", "youtube_searched_for",
  "zoom_in", "zoom_out", "add_alert", "auto_delete", "error", "error_outline", "notification_important",
  "warning", "warning_amber", "10k", "1k", "1k_plus", "2k", "2k_plus", "3k", "3k_plus", "4k", "4k_plus",
  "5k", "5k_plus", "6k", "6k_plus", "7k", "7k_plus", "8k", "8k_plus", "9k", "9k_plus", "add_to_queue",
  "airplay", "album", "art_track", "av_timer", "branding_watermark", "call_to_action", "closed_caption",
  "closed_caption_disabled", "closed_caption_off", "control_camera", "equalizer", "explicit", "fast_forward",
  "fast_rewind", "featured_play_list", "featured_video", "fiber_dvr", "fiber_manual_record", "fiber_new",
  "fiber_pin", "fiber_smart_record", "forward_10", "forward_30", "forward_5", "games", "hd", "hearing",
  "hearing_disabled", "high_quality", "library_add", "library_add_check", "library_books", "library_music",
  "loop", "mic", "mic_none", "mic_off", "missed_video_call", "movie", "movie_creation", "movie_filter",
  "music_video", "new_releases", "not_interested", "note", "pause", "pause_circle", "pause_circle_filled",
  "pause_circle_outline", "play_arrow", "play_circle", "play_circle_filled", "play_circle_outline",
  "play_disabled", "playlist_add", "playlist_add_check", "playlist_play", "queue", "queue_music",
  "queue_play_next", "radio", "recent_actors", "remove_from_queue", "repeat", "repeat_on", "repeat_one",
  "repeat_one_on", "replay", "replay_10", "replay_30", "replay_5", "replay_circle_filled", "sd",
  "skip_next", "skip_previous", "slow_motion_video", "snooze", "sort_by_alpha", "speed", "stop",
  "stop_circle", "subscriptions", "subtitles", "subtitles_off", "surround_sound", "video_call",
  "video_label", "video_library", "video_settings", "videocam", "videocam_off", "volume_down",
  "volume_mute", "volume_off", "volume_up", "web", "web_asset", "web_asset_off", "add_ic_call",
  "alternate_email", "app_registration", "business", "call", "call_end", "call_made", "call_merge",
  "call_missed", "call_missed_outgoing", "call_received", "call_split", "cancel_presentation",
  "chat", "chat_bubble", "chat_bubble_outline", "clear_all", "comment", "contact_mail", "contact_phone",
  "contacts", "desktop_access_disabled", "dialer_sip", "dialpad", "document_scanner", "domain_disabled",
  "domain_verification", "duo", "email", "forum", "forward_to_inbox", "hourglass_bottom", "hourglass_empty",
  "hourglass_full", "hourglass_top", "import_contacts", "import_export", "invert_colors_off", "list_alt",
  "live_help", "location_off", "location_on", "mail_outline", "mark_chat_read", "mark_chat_unread",
  "mark_email_read", "mark_email_unread", "message", "mobile_screen_share", "more_time", "nat",
  "no_sim", "pause_presentation", "person_add_disabled", "person_search", "phone", "phone_disabled",
  "phone_enabled", "phonelink_erase", "phonelink_lock", "phonelink_ring", "phonelink_setup",
  "portable_wifi_off", "present_to_all", "print_disabled", "qr_code", "qr_code_2", "qr_code_scanner",
  "read_more", "ring_volume", "rss_feed", "screen_share", "sentiment_satisfied_alt", "speaker_phone",
  "stay_current_landscape", "stay_current_portrait", "stay_primary_landscape", "stay_primary_portrait",
  "stop_screen_share", "swap_calls", "textsms", "unsubscribe", "voicemail", "vpn_key", "wifi_calling",
  "add_chart", "add_comment", "align_horizontal_center", "align_horizontal_left", "align_horizontal_right",
  "align_vertical_bottom", "align_vertical_center", "align_vertical_top", "attach_file", "attach_money",
  "auto_graph", "bar_chart", "border_all", "border_bottom", "border_clear", "border_color", "border_horizontal",
  "border_inner", "border_left", "border_outer", "border_right", "border_style", "border_top", "border_vertical",
  "bubble_chart", "checklist", "checklist_rtl", "copy_all", "create", "drag_handle", "draw", "edit",
  "edit_note", "format_align_center", "format_align_justify", "format_align_left", "format_align_right",
  "format_bold", "format_clear", "format_color_fill", "format_color_reset", "format_color_text",
  "format_indent_decrease", "format_indent_increase", "format_italic", "format_line_spacing",
  "format_list_bulleted", "format_list_numbered", "format_list_numbered_rtl", "format_paint",
  "format_quote", "format_shapes", "format_size", "format_strikethrough", "format_textdirection_l_to_r",
  "format_textdirection_r_to_l", "format_underlined", "functions", "height", "horizontal_distribute",
  "horizontal_rule", "insert_chart", "insert_chart_outlined", "insert_comment", "insert_drive_file",
  "insert_emoticon", "insert_invitation", "insert_link", "insert_photo", "inventory", "inventory_2",
  "layers", "layers_clear", "linear_scale", "link", "link_off", "list", "lookup", "margin", "mode",
  "mode_comment", "mode_edit", "mode_edit_outline", "monetization_on", "money_off", "money_off_csred",
  "multiline_chart", "notes", "padding", "pages", "pie_chart", "pie_chart_outline", "pie_chart_outlined",
  "post_add", "publish", "query_stats", "scatter_plot", "score", "short_text", "show_chart", "space_bar",
  "stacked_line_chart", "strikethrough_s", "subscript", "superscript", "table_chart", "table_rows",
  "text_fields", "title", "vertical_align_bottom", "vertical_align_center", "vertical_align_top",
  "vertical_distribute", "wrap_text", "approval", "attach_email", "attachment", "cloud", "cloud_circle",
  "cloud_done", "cloud_off", "cloud_queue", "cloud_upload", "create_new_folder", "download", "download_done",
  "download_for_offline", "downloading", "drive_file_move", "drive_file_move_outline", "drive_file_move_rtl",
  "drive_file_rename_outline", "drive_folder_upload", "file_download", "file_download_done",
  "file_download_off", "file_present", "file_upload", "folder", "folder_open", "folder_shared",
  "folder_zip", "format_overline", "grid_view", "request_quote", "rule_folder", "snippet_folder",
  "text_snippet", "topic", "upload", "upload_file", "workspaces", "workspaces_filled", "workspaces_outline",
  "browser_not_supported", "browser_updated", "cast", "cast_connected", "cast_for_education",
  "computer", "connected_tv", "desktop_mac", "desktop_windows", "developer_board", "developer_board_off",
  "device_hub", "device_thermostat", "device_unknown", "devices", "devices_other", "dock", "earbuds",
  "earbuds_battery", "gamepad", "headphones", "headphones_battery", "headset", "headset_mic", "headset_off",
  "home_max", "home_mini", "keyboard", "keyboard_alt", "keyboard_capslock", "keyboard_hide",
  "keyboard_return", "keyboard_tab", "keyboard_voice", "laptop", "laptop_chromebook", "laptop_mac",
  "laptop_windows", "memory", "monitor", "mouse", "phone_android", "phone_iphone", "phonelink",
  "phonelink_off", "point_of_sale", "power_input", "router", "screen_lock_landscape", "screen_lock_portrait",
  "screen_lock_rotation", "screen_rotation", "screen_search_desktop", "security_update", "security_update_good",
  "security_update_warning", "sensor_door", "sensor_window", "smart_screen", "smart_toy", "smartphone",
  "speaker", "speaker_group", "tablet", "tablet_android", "tablet_mac", "toys", "tv", "tv_off",
  "videogame_asset", "videogame_asset_off", "watch", "sensor_door", "sensor_window", "shield",
  "stop_screen_share", "vibration", "video_label", "video_library", "video_settings", "videocam",
  "videocam_off", "volume_down", "volume_mute", "volume_off", "volume_up", "web", "web_asset",
  "web_asset_off", "add_ic_call", "alternate_email", "app_registration", "business", "call", "call_end",
  "call_made", "call_merge", "call_missed", "call_missed_outgoing", "call_received", "call_split",
  "cancel_presentation", "chat", "chat_bubble", "chat_bubble_outline", "clear_all", "comment",
  "contact_mail", "contact_phone", "contacts", "desktop_access_disabled", "dialer_sip", "dialpad",
  "document_scanner", "domain_disabled", "domain_verification", "duo", "email", "forum", "forward_to_inbox",
  "hourglass_bottom", "hourglass_empty", "hourglass_full", "hourglass_top", "import_contacts",
  "import_export", "invert_colors_off", "list_alt", "live_help", "location_off", "location_on",
  "mail_outline", "mark_chat_read", "mark_chat_unread", "mark_email_read", "mark_email_unread",
  "message", "mobile_screen_share", "more_time", "nat", "no_sim", "pause_presentation", "person_add_disabled",
  "person_search", "phone", "phone_disabled", "phone_enabled", "phonelink_erase", "phonelink_lock",
  "phonelink_ring", "phonelink_setup", "portable_wifi_off", "present_to_all", "print_disabled", "qr_code",
  "qr_code_2", "qr_code_scanner", "read_more", "ring_volume", "rss_feed", "screen_share",
  "sentiment_satisfied_alt", "speaker_phone", "stay_current_landscape", "stay_current_portrait",
  "stay_primary_landscape", "stay_primary_portrait", "stop_screen_share", "swap_calls", "textsms",
  "unsubscribe", "voicemail", "vpn_key", "wifi_calling",
  "diamond", "rocket", "rocket_launch", "bolt", "energy_savings_leaf", "eco", "recycling", "water_drop",
  "sunny", "bedtime", "cloudy", "rainy", "thunderstorm", "snowing", "wind_power", "solar_power",
  "directions_car", "directions_bus", "directions_bike", "directions_walk", "directions_run", "flight",
  "train", "subway", "tram", "local_taxi", "sailing", "kayaking", "hiking", "skateboarding",
  "sports_basketball", "sports_soccer", "sports_tennis", "sports_baseball", "sports_volleyball",
  "sports_football", "sports_cricket", "sports_golf", "sports_mma", "sports_kabaddi", "fitness_center",
  "monitor_heart", "health_and_safety", "medical_services", "vaccines", "coronavirus", "mask",
  "potted_plant", "forest", "nature", "nature_people", "agriculture", "cruelty_free", "pets",
  "restaurant", "fastfood", "local_pizza", "local_cafe", "local_bar", "liquor", "icecream", "cake",
  "celebration", "festival", "nightlife", "theater_comedy", "music_note", "piano", "guitar", "drum_set",
  "palette", "brush", "architecture", "design_services", "edit_square", "ink_pen", "draw",
  "computer", "laptop", "smartphone", "tablet", "watch", "headphones", "speaker", "keyboard",
  "mouse", "joystick", "memory", "cpu", "terminal", "database", "cloud", "wifi", "bluetooth",
  "lock", "key", "shield", "security", "policy", "fingerprint", "face_unlock", "password",
  "shopping_cart", "shopping_bag", "store", "sell", "loyalty", "coupon", "payments", "wallet",
  "account_balance", "trending_up", "trending_down", "show_chart", "bar_chart", "pie_chart",
  "public", "language", "translate", "map", "explore", "navigation", "flag", "push_pin",
  "mail", "send", "inbox", "drafts", "archive", "delete", "report", "spam",
  "call", "chat", "forum", "groups", "person", "person_add", "contact_page", "contacts",
  "calendar_today", "event", "schedule", "alarm", "timer", "hourglass_empty", "history",
  "lightbulb", "tips_and_updates", "auto_fix_high", "psychology", "science", "school", "menu_book",
  "work", "business_center", "campaign", "announcement", "notifications", "priority_high",
  "thumb_up", "thumb_down", "favorite", "star", "bookmark", "verified", "new_releases",
  "image", "camera_alt", "videocam", "mic", "movie", "audiotrack", "play_circle", "pause_circle"
];
